saasapp/config/routes.rb
Rails.application.routes.draw do
    
  devise_for :users
  devise_for :views
  devise_for :models
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'menards_callsheet', to: 'pages#menards_callsheet'
  get 'orders', to: 'pages#orders'
  get 'map', to: 'pages#map'
  resources :stores
  resources :users do
    resource :profiles
  end
end

saasapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

saasapp/app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

saasapp/app/models/store.rb
class Store < ActiveRecord::Base
end

saasapp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

saasapp/app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

saasapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

saasapp/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        @stores = Store.all
    end
    
    def menards_callsheet
    end
    
    def about
    end
    
    def orders
    end
    
    def map
        @stores = Store.all
    end
    
    private
    # don't know what this does yet, "Use callbacks to share common setup or constraints between actions"
    def set_store
    @store = Store.find(params[:id])
    end
    
    
    def store_params
        params.require(:store).permit(:yard, :abbrv, :name, :prototype, :address, :city, :state, :zipcode, :lat, :long, :phone, :service_rep, :user_id, :notes, :lastvisit, :created_at, :updated_at)
    end

end

saasapp/app/controllers/stores_controller.rb
class StoresController < ApplicationController
    
    def index
        @stores = Store.all
    end
    
    def new
    end
    
    private
        # don't know what this does yet, "Use callbacks to share common setup or constraints between actions"
        def set_store
        @store = Store.find(params[:id])
        end
        
        
        def store_params
            params.require(:store).permit(:yard, :abbrv, :name, :prototype, :address, :city, :state, :zipcode, :lat, :long, :phone, :service_rep, :user_id, :notes, :lastvisit, :created_at, :updated_at)
        end

end

saasapp/app/controllers/users_controller.rb
class UsersController < ApplicationController

end

saasapp/app/helpers/application_helper.rb
module ApplicationHelper
end

saasapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SRS Employee Portal</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="DataTables-1.10.12/css/dataTables.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="AutoFill-2.1.2/css/autoFill.bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="Buttons-1.2.2/css/buttons.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="ColReorder-1.3.2/css/colReorder.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="FixedColumns-3.2.2/css/fixedColumns.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="FixedHeader-3.1.2/css/fixedHeader.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="Responsive-2.1.0/css/responsive.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="Select-1.2.0/css/select.bootstrap.min.css"/>
    <script type="text/javascript" src="jQuery-2.2.3/jquery-2.2.3.min.js"></script>
    <script type="text/javascript" src="pdfmake-0.1.18/build/pdfmake.min.js"></script>
    <script type="text/javascript" src="pdfmake-0.1.18/build/vfs_fonts.js"></script>
    <script type="text/javascript" src="DataTables-1.10.12/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="DataTables-1.10.12/js/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript" src="AutoFill-2.1.2/js/dataTables.autoFill.min.js"></script>
    <script type="text/javascript" src="AutoFill-2.1.2/js/autoFill.bootstrap.min.js"></script>
    <script type="text/javascript" src="Buttons-1.2.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="Buttons-1.2.2/js/buttons.bootstrap.min.js"></script>
    <script type="text/javascript" src="Buttons-1.2.2/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="Buttons-1.2.2/js/buttons.print.min.js"></script>
    <script type="text/javascript" src="ColReorder-1.3.2/js/dataTables.colReorder.min.js"></script>
    <script type="text/javascript" src="FixedColumns-3.2.2/js/dataTables.fixedColumns.min.js"></script>
    <script type="text/javascript" src="FixedHeader-3.1.2/js/dataTables.fixedHeader.min.js"></script>
    <script type="text/javascript" src="Responsive-2.1.0/js/dataTables.responsive.min.js"></script>
    <script type="text/javascript" src="Responsive-2.1.0/js/responsive.bootstrap.min.js"></script>
    <script type="text/javascript" src="Select-1.2.0/js/dataTables.select.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top navbar-bg" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "//www.strategicretailsolutions.com", class: "navbar-brand" do %>
            Strategic Retail Solutions //
          <% end %>
          <%= link_to "#", class: "navbar-brand" do %>
            <i class="fa fa-group"></i>
            Rep Portal
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Product Lines <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Colonial Elegance</a></li>
                <li><a href="#">Genie</a></li>
                <li><a href="#">Honeywell</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">All Stone</a></li>
                <li><a href="#">Tuscany</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Rep Tools <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Literature Requests", about_path %></li>
                <li><%= link_to "Call Sheets", menards_callsheet_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Store List", stores_path %></li>
                <li><%= link_to "Territory Map", map_path %></li>
                <li><%= link_to "Orders Testbench", orders_path %></li>
              </ul>
            </li>
            <li><%= link_to "Log Out", about_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>






      <%= yield %>

  </body>
</html>

saasapp/app/views/pages/about.html.erb
<h1>About Page</h1>

saasapp/app/views/pages/home.html.erb
    <h1 class="text-center">Store List</h1>
    <div class="container-fluid">
      <table class="table-sm">
        <thead class="thead-inverse">
          <tr>
            <th >Yard #</th>
            <th>Abbreviation</th>
            <th>Name</th>
            <th>Prototype</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Zip</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Phone #</th>
            <th>Service Rep</th>
            <th>User ID</th>
            <th>Notes</th>
            <th>Last Visit</th>
            <th>Created At</th>
            <th>Updated At</th>
          </tr>
        </thead>
        <tbody class="table-striped table-hover">
          <% @stores.each do |store| %>
            <tr>
              <td><%= store.yard %></td>
              <td><%= store.abbrv %></td>
              <td><%= store.name %></td>
              <td><%= store.prototype %></td>
              <td><%= store.address %></td>
              <td><%= store.city %></td>
              <td><%= store.state %></td>
              <td><%= store.zipcode %></td>
              <td><%= store.lat %></td>
              <td><%= store.long %></td>
              <td><%= store.phone %></td>
              <td><%= store.service_rep %></td>
              <td><%= store.user_id %></td>
              <td><%= store.notes %></td>
              <td><%= store.lastvisit %></td>
              <td><%= store.created_at %></td>
              <td><%= store.updated_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

saasapp/app/views/pages/map.html.erb
<!-- API Key: AIzaSyDTkGBrmI1dNAITzfWSXP1rcPS3S2YvO_o -->
<script src="//maps.google.com/maps/api/js?key=AIzaSyDTkGBrmI1dNAITzfWSXP1rcPS3S2YvO_o"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script>
  handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 0,
      "lng": 0,
      "picture": {
        "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
        "width":  32,
        "height": 32
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>


<div class="col-md-6 col-md-offset-3">
  <div class="well">
      <div id="map" style='width: 800px; height: 400px;'></div>
  </div>
</div>

saasapp/app/views/pages/orders.html.erb
<div class="col-md-6">
  <div class="well">
    <div>
      <a href="https://apps.commercehub.com/account/login?service=https://dsm.commercehub.com/dsm/shiro-cas">Click here to login first</a>
      <iframe src="https://dsm.commercehub.com/dsm/gotoOrderRealmForm.do?action=web_quickship&status=open&substatus=no-activity&merchant=thehomedepot" width=100% height="1000"></iframe>
    </div>
  </div>
</div>

saasapp/app/views/stores/index.html.erb
<script>
  $(document).ready(function() {
    $('#store-table').DataTable( {
        "order": [[ 2, "desc" ]]
    } );
} );
</script>

<div class="container-fluid">
  <div class="well">
    <h1 class="text-center">Store List</h1>
    <div class="container-fluid">
      <table id="store-table" class="table table-striped table-bordered table-hover">
        <thead bgcolor="#969696" style="color: white">
          <tr>
            <th><div style='width: 20px'>Yard</div></th>
            <th><div style='width: 20px'>Abbv</div></th>
            <th><div style='width: 70px'>Name</div></th>
            <th><div style='width: 50px'>Prototype</div></th>
            <th><div style='width: 190px'>Address</div></th>
            <th><div style='width: 80px'>City</div></th>
            <th><div style='width: 25px'>State</div></th>
            <th><div style='width: 50px'>Zip</div></th>
            <th><div style='width: 50px'>Phone</div></th>
            <th><div style='width: 110px'>Service Rep</div></th>
            <th><div style='width: 75px'>Last Visit</div></th>
            <th><div style='width: 350px'>Notes</div></th>
            <th><div style='width: 170px'>Entry Creation Date</div></th>
            <th><div style='width: 170px'>Entry Last Update</div></th>
            <th><div style='width: 50px'>Latitude</div></th>
            <th><div style='width: 50px'>Longitude</div></th>
            <th><div style='width: 40px'>UID</div></th>
          </tr>
        </thead>
        <tbody>
          <% @stores.each do |store| %>
            <tr>
              <td><%= store.yard %></td>
              <td><%= store.abbrv %></td>
              <td><%= store.name %></td>
              <td><%= store.prototype %></td>
              <td><%= store.address %></td>
              <td><%= store.city %></td>
              <td><%= store.state %></td>
              <td><%= store.zipcode %></td>
              <td><%= store.phone %></td>
              <td><%= store.service_rep %></td>
              <td><%= store.lastvisit %></td>
              <td><%= store.notes %></td>
              <td><%= store.created_at %></td>
              <td><%= store.updated_at %></td>
              <td><%= store.lat %></td>
              <td><%= store.long %></td>
              <td><%= store.user_id %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>